{
 "title": "Cronjob Dashboard- WIP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Input DataSource", "query": "prometheus" },
   { "name": "cluster", "label": "Select Cluster", "query": { "query": "kube_namespace_created" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "kube_pod_container_info{cluster=~\"$cluster\"}"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Job Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_cronjob_info{cluster=\"$cluster\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "kube_cronjob_spec_successful_job_history_limit{cluster=\"$cluster\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "kube_cronjob_spec_failed_job_history_limit{cluster=\"$cluster\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Jobs Completed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_job_status_completion_time{cluster=\"$cluster\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "  topk(1, sort_desc(kube_job_status_completion_time{cluster=\"$cluster\", namespace=~\"$namespace\"}))\r\n-\r\n  (\r\n      kube_job_status_start_time\r\n    and on (job_name)\r\n      topk(1, sort_desc(kube_job_status_completion_time{cluster=\"$cluster\", namespace=~\"$namespace\"}))\r\n  )"
    }
   ]
  },
  {
   "title": "Total Jobs Active",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\",cluster=~\"$cluster\"}) ",
     "legendFormat": "{{label_value}}"
    }
   ]
  },
  {
   "title": "Active Job List",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "kube_job_status_active{namespace=~\"$namespace\",cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "kube_job_status_failed{cluster=\"$cluster\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Suspended Job",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_cronjob_spec_suspend{cluster=\"$cluster\",namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}