{
 "title": "My Workspace Copy",
 "description": "Personal Workspace",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace(Job)",
    "query": {
     "query": "label_values(kube_job_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Job Active Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_active{namespace=~\"$namespace\",job_name=~\"(helloworld.*)\"})",
     "legendFormat": "{{total job}}"
    }
   ]
  },
  {
   "title": "Jobs Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_complete{namespace=~\"$namespace\",job_name=~\"(helloworld.*)\",condition=\"true\"})",
     "legendFormat": "{{total job}}"
    }
   ]
  },
  {
   "title": "Jobs Successful",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_complete{namespace=~\"$namespace\",job_name=~\"(helloworld.*)\",condition=\"true\"})",
     "legendFormat": "{{total job}}"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_failed{namespace=~\"$namespace\",job_name=~\"(helloworld.*)\"}==1)",
     "legendFormat": "{{total job}}"
    }
   ]
  },
  {
   "title": "Job Running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{job_name=~\"(helloworld.*)\"})",
     "legendFormat": "{{total job}}"
    }
   ]
  },
  {
   "title": "Time Taken By last Successful Job",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  topk(1, sort_desc(kube_job_status_completion_time{job_name=~\"(helloworld.*)\"}))\r\n-\r\n  (\r\n      kube_job_status_start_time\r\n    and on (job_name)\r\n      topk(1, sort_desc(kube_job_status_completion_time{job_name=~\"(helloworld.*)\"}))\r\n  )",
     "legendFormat": "{{total job}}"
    }
   ]
  },
  {
   "title": "Last Successful Job",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "topk(1, sort_desc(kube_job_status_completion_time{job_name=~\"(helloworld.*)\"}))",
     "legendFormat": "{{ job_name }}"
    }
   ]
  },
  {
   "title": "Failed Job List",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": " clamp_max(\r\n      (label_replace(\r\n      label_replace(\r\n        max(\r\n          kube_job_status_start_time\r\n          * ON(job_name,namespace) GROUP_RIGHT()\r\n          kube_job_owner{owner_name!=\"\"}\r\n        )\r\n        BY (job_name, owner_name, namespace)\r\n        == ON(owner_name) GROUP_LEFT()\r\n        max(\r\n          kube_job_status_start_time\r\n          * ON(job_name,namespace) GROUP_RIGHT()\r\n          kube_job_owner{owner_name!=\"\"}\r\n        )\r\n        BY (owner_name),\r\n      \"job\", \"$1\", \"job_name\", \"(.+)\"),\r\n    \"cronjob\", \"$1\", \"owner_name\", \"(.+)\")),1)\r\n      * ON(job) GROUP_LEFT()\r\n      label_replace(\r\n        label_replace(\r\n          (kube_job_status_failed != 0),\r\n          \"job\", \"$1\", \"job_name\", \"(.+)\"),\r\n        \"cronjob\", \"$1\", \"owner_name\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "Last Job Start At",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_job_status_start_time{job_name=~\"(helloworld.*)\"}) * 1000",
     "legendFormat": "{{total job}}"
    }
   ]
  },
  {
   "title": "Last Job Completed At",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_job_status_completion_time{job_name=~\"(helloworld-.*)\"}) * 1000",
     "legendFormat": "{{total job}}"
    }
   ]
  },
  {
   "title": "Latest Job Created At",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_job_created{job_name=~\"(helloworld.*)\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}